repos:
  - repo: local
    hooks:
      # Run the linter.
      - id: ruff
        name: Ruff linter
        entry: ruff check
        language: system
        types_or: [ python ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        entry: ruff format
        language: system
        name: Ruff formatter
        types_or: [ python ]